name: gnucash_mobile
description: "An application for keeping track of Gnucash transactions on the go."

publish_to: 'none'

version: 1.0.8+3

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  csv: ^6.0.0
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dart_extensions_methods: ^2.0.0
  flutter_native_splash: ^2.4.1
  logger: ^2.4.0
  uuid: ^4.5.0
  animations: ^2.0.11
  animated_tree_view: ^2.3.0
  flutter_slidable: ^3.1.1
  share_plus: ^10.0.2

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/gnucash_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/gnucash_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/gnucash_logo.png